apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-multipath-fc-udev-quantastor
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/multipath.conf
          mode: 0644
          contents:
            source:
              data: |
                devices {
                  device {
                    failback "immediate"
                    fast_io_fail_tmo 15
                    flush_on_last_del "yes"
                    getuid_callout "/lib/udev/scsi_id --whitelisted --replace-whitespace --device=/dev/%n"
                    hardware_handler "1 alua"
                    no_path_retry "queue"
                    path_checker "tur"
                    path_grouping_policy "group_by_prio"
                    prio "alua"
                    product "QUANTASTOR"
                    rr_min_io 100
                    rr_weight "uniform"
                    user_friendly_names "no"
                    vendor "OSNEXUS"
                  }
                }
                blacklist {
                  devnode ".*"
                  devnode "!^(sd[a-z]|dasd[a-z]|nvme[0-9])"
                }
                blacklist_exceptions {
                  property "(ID_SCSI_VPD|ID_WWN|ID_SERIAL)"
                  device {
                      vendor "OSNEXUS"
                      product "QUANTASTOR"
                  }
                }

        - path: /etc/modprobe.d/quantastor.conf
          mode: 0644
          contents:
            source:
              data: |
                # Emulex
                options lpfc lpfc_hba_queue_depth=4096 lpfc_lun_queue_depth=128
                # QLogic
                options qla2xxx ql2xmaxqdepth=128
                # Cisco
                options fnic fnic_max_qdepth=128

        - path: /etc/udev/rules.d/99-osnexus-queue.rules
          mode: 0644
          contents:
            source:
              data: |
                ACTION=="add|change", KERNEL=="sd[a-z]*", SUBSYSTEM=="block", ENV{ID_VENDOR}=="OSNEXUS", ATTR{queue/scheduler}="none"
                ACTION=="add|change", KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_SERIAL}=="36742b0f*", ATTR{queue/scheduler}="none"
                # https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/monitoring_and_managing_system_status_and_performance/factors-affecting-i-o-and-file-system-performance_monitoring-and-managing-system-status-and-performance#generic-block-device-tuning-parameters_factors-affecting-i-o-and-file-system-performance
                ACTION=="add|change", KERNEL=="sd[a-z]*", SUBSYSTEM=="block", ENV{ID_VENDOR}=="OSNEXUS", ATTR{queue/add_random}="0"
                ACTION=="add|change", KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_SERIAL}=="36742b0f*", ATTR{queue/add_random}="0"
                # For storage configurations that need to maximize distribution of completion processing setting this option to '2' forces the completion to run on the requesting cpu (bypassing the "group" aggregation logic).
                ACTION=="add|change", KERNEL=="sd[a-z]*", SUBSYSTEM=="block", ENV{ID_VENDOR}=="OSNEXUS", ATTR{queue/rq_affinity}="2"
                ACTION=="add|change", KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_SERIAL}=="36742b0f*", ATTR{queue/rq_affinity}="2"

    systemd:
      units:
        - name: multipathd.service
          enabled: true
