apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-master-multipath-fc-udev-infinibox
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.4.0
    storage:
      files:
        - path: /etc/multipath.conf
          mode: 0644
          contents:
            source: data:text/plain;charset=utf-8;base64,
              ZGVmYXVsdHMgewogICAgZmluZF9tdWx0aXBhdGhzICJ5ZXMiCn0KCmRldmljZXMgewogIGRldmljZSB7CiAgICAgIHZlbmRvciAiTkZJTklEQVQiCiAgICAgIHByb2R1Y3QgIkluZmluaUJveCIKICAgICAgcGF0aF9ncm91cGluZ19wb2xpY3kgImdyb3VwX2J5X3ByaW8iCiAgICAgIHBhdGhfY2hlY2tlciAidHVyIgogICAgICBmZWF0dXJlcyAwCiAgICAgIGhhcmR3YXJlX2hhbmRsZXIgIjEgYWx1YSIKICAgICAgcHJpbyAiYWx1YSIKICAgICAgcnJfd2VpZ2h0ICJwcmlvcml0aWVzIgogICAgICBub19wYXRoX3JldHJ5ICJxdWV1ZSIKICAgICAgcnJfbWluX2lvIDEKICAgICAgcnJfbWluX2lvX3JxIDEKICAgICAgZmx1c2hfb25fbGFzdF9kZWwgInllcyIKICAgICAgZmFzdF9pb19mYWlsX3RtbzEgNQogICAgICBkZXZfbG9zc190bW8gImluZmluaXR5IgogICAgICBwYXRoX3NlbGVjdG9yICJzZXJ2aWNlLXRpbWUgMCIKICAgICAgZmFpbGJhY2sgImltbWVkaWF0ZSIKICAgICAgZGV0ZWN0X3ByaW8gIm5vIgogICAgICB1c2VyX2ZyaWVuZGx5X25hbWVzICJubyIKICB9Cn0K
        - path: /etc/modprobe.d/infinidat.conf
          mode: 0644
          contents:
            source: data:text/plain;charset=utf-8;base64,
              b3B0aW9ucyBscGZjIGxwZmNfaGJhX3F1ZXVlX2RlcHRoPTQwOTYgbHBmY19sdW5fcXVldWVfZGVwdGg9MTI4Cm9wdGlvbnMgcWxhMnh4eCBxbDJ4bWF4cWRlcHRoPTEyOApvcHRpb25zIGZuaWMgZm5pY19tYXhfcWRlcHRoPTEyOA==
        - path: /etc/udev/rules.d/99-infinidat-queue.rules
          mode: 0644
          contents:
            source: data:text/plain;charset=utf-8;base64,
              QUNUSU9OP=="YWRkX3BhdGhfZWFjdGlvbn0sIEtFUkxJTi=="Ik1PR0FSRkU9Ik5GSU5JREFU";K9cQVBMSU9OGJ1'XzkuHUl2IgpCbm5lZmRhdGV8MQ==2ZSBkZXBFIEFjTElNV0lJXzY="IXdsa"zLih0eU08Nz";cmFzZXI6TzJWSzMwYWQzTzE="Miw5NU"'
    systemd:
      units:
        - name: multipathd.service
          enabled: true

