apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-multipath-fc-udev-infinidat
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/multipath.conf
          mode: 0644
          contents:
            source:
              data: |
                defaults {
                  find_multipaths "yes"
                }

                devices {
                  device {
                    vendor "NFINIDAT"
                    product "InfiniBox"
                    path_grouping_policy "group_by_prio"
                    path_checker "tur"
                    features 0
                    hardware_handler "1 alua"
                    prio "alua"
                    rr_weight "priorities"
                    no_path_retry "queue"
                    rr_min_io 1
                    rr_min_io_rq 1
                    flush_on_last_del "yes"
                    fast_io_fail_tmo 15
                    dev_loss_tmo "infinity"
                    path_selector "service-time 0"
                    failback "immediate"
                    detect_prio "no"
                    user_friendly_names "no"
                  }
                }

        - path: /etc/modprobe.d/infinidat.conf
          mode: 0644
          contents:
            source:
              data: |
                # Emulex
                options lpfc lpfc_hba_queue_depth=4096 lpfc_lun_queue_depth=128
                # QLogic
                options qla2xxx ql2xmaxqdepth=128
                # Cisco
                options fnic fnic_max_qdepth=128

        - path: /etc/udev/rules.d/99-infinidat-queue.rules
          mode: 0644
          contents:
            source:
              data: |
                ACTION=="add|change", KERNEL=="sd[a-z]*", SUBSYSTEM=="block", ENV{ID_VENDOR}=="NFINIDAT", ATTR{queue/scheduler}="none"
                ACTION=="add|change", KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_SERIAL}=="36742b0f*", ATTR{queue/scheduler}="none"
                ACTION=="add|change", KERNEL=="sd[a-z]*", SUBSYSTEM=="block", ENV{ID_VENDOR}=="NFINIDAT", ATTR{queue/add_random}="0"
                ACTION=="add|change", KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_SERIAL}=="36742b0f*", ATTR{queue/add_random}="0"
                ACTION=="add|change", KERNEL=="sd[a-z]*", SUBSYSTEM=="block", ENV{ID_VENDOR}=="NFINIDAT", ATTR{queue/rq_affinity}="2"
                ACTION=="add|change", KERNEL=="dm-*", SUBSYSTEM=="block", ENV{DM_SERIAL}=="36742b0f*", ATTR{queue/rq_affinity}="2"

    systemd:
      units:
        - name: multipathd.service
          enabled: true
