kind: Secret
apiVersion: v1
metadata:
  name: load-cloud-init-secret
  namespace: vm-density
stringData:
  userData: |
    #cloud-config
    user: admin
    password: Welcome11
    chpasswd: { expire: False }
    ssh_pwauth: true
    timezone: "America/New_York"
    write_files:
    - path: /etc/systemd/system/fio-load.service
      permissions: "0755"
      content: |
        # Systemd unit file for running the fio-load service
        # Use to view service logs:
        # journalctl -u fio-load
        
        [Unit]
        Description=FIO Load Service
        
        [Service]
        Type=oneshot
        RemainAfterExit=true
        ExecStart=fio --name=randrw --rw=randrw --direct=1 --ioengine=libaio --bs=16k --numjobs=2 --rwmixread=90 --size=512M --runtime=600 --group_reporting

        [Install]
        WantedBy=multi-user.target
        
        Restart=on-failure
        RestartSec=3
    runcmd:
        # https://www.reddit.com/r/bash/comments/hblss4/logging_cloudinit_script_to_console/
        - exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
        - sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
        - grubby --args=ipv6.disable=1 --update-kernel=ALL
        - dnf install sysstat fio -y
        - systemctl daemon-reload
        - iostat -N -h -x -t -m
    
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: {{ item.1 }}
  namespace: vm-density
spec:
  dataVolumeTemplates:
    - kind: DataVolume
      metadata:
        name: "{{ item.1 }}-pvc"
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          storageClassName: infinibox-storageclass-fc
          resources:
            requests:
              storage: 5Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        externalService: "{{ item.1 }}-ssh-service"
    spec:
      domain:
        clock:
          timer: {}
          timezone: America/New York
        cpu:
          sockets: 2
          cores: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi:
            enabled: true
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory:  2Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: rootdisk
          dataVolume:
            name: "{{ item.1 }}-pvc"
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: load-cloud-init-secret
